# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-11 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_patient', models.TextField(blank=True, null=True)),
                ('msg_doctor', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('disapproved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('diseases', models.CharField(blank=True, max_length=300, null=True)),
                ('token_no', models.CharField(blank=True, max_length=55, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports', verbose_name=' ')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
