# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210111_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report_generated',
            field=models.BooleanField(default=False),
        ),
    ]
