# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-11 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=25, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('category', models.CharField(choices=[('def', 'Choose Category'), ('den', 'Dentist'), ('pat', 'Pathologist'), ('neu', 'Neurologist'), ('hts', 'Heart Specialist'), ('vhs', 'Voice & Hearing Specialist'), ('car', 'Cardiologist'), ('rad', 'Radiologist'), ('lks', 'Lungs & Kidney Specialist')], default='def', max_length=3)),
                ('awards', models.ManyToManyField(blank=True, to='doctor.Award')),
                ('doctor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
