# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-11 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('Choose Category', 'Choose Category'), ('Dentist', 'Dentist'), ('Nephrologist', 'Nephrologist'), ('Endocrinologist', 'Endocrinologists'), ('Ophthalmologist', 'Ophthalmologist'), ('Cardiologist', 'Cardiologist'), ('Allergist', 'Allergist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist')], default='def', max_length=33),
        ),
    ]
